version: '3.4'

services:
  tiendaservicios.api.autor:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapiautor
    build:
      context: .
      dockerfile: TiendaServicios.Api.Autor/Dockerfile
  tiendaservicios.api.libro:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapilibro
    build:
      context: .
      dockerfile: TiendaServicios.Api.Libro/Dockerfile

  tiendaservicios.api.carritocompra:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapicarritocompra
    build:
      context: .
      dockerfile: TiendaServicios.Api.CarritoCompra/Dockerfile

  tiendaservicios.api.gateway2:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapigateway2
    build:
      context: .
      dockerfile: ../TiendaServicios.Api.Gateway2/Dockerfile

  tiendaservicios.api.gateway5:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapigateway5
    build:
      context: .
      dockerfile: ../TiendaServicios.Api.Gateway5/Dockerfile

networks:
  default:
     external:
        name: microservicenet




